### ISSUE TITLE
Failed to load sounds, resource not found

### ISSUE THREAD

**Issue by Tomptez** [ShavaShav/react-native-soundfont#2]
I've been trying to get this to work for a while and for some reason I am not able to load any sounds.

If I try to load an instrument like this

    SoundFont.instrument('piano', {
      notes: ['A3'] ,
    })

I get
    Console Warning
    Failed to load "A3" (piano) from "undefined":{"message":"resource not found","code":-1}

When I import
    import Sound from 'react-native-sound';

    Sound.DOCUMENT

and

    Sound.MAIN_BUNDLE

both return undefined.

I I try to manually provide an absolute path I get

    Console Warning
    Failed to load "A3" (piano) from "aboslute_path_to_project/android/app/src/main/res/raw/":{"message":"resource not found","code":-1}

The sound file is provided as piano_A3.mp3

Is this a bug or am I doing something completely wrong?

Edit:
Also when running react-native run-android I get "android/app/src/main/res/raw/piano_A3.mp3: Error: 'A' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore" I tried to place the file in a different folder and use it via "path" but that doesn't work either.

**Comment by Tomptez** [comment]
Okay I kinda solved it myself.
I just had to lowercase the soundfile and it worked.
For some reason the archives in https://github.com/ShavaShav/react-native-soundfonts so not work, so I couldn't work with them or I would've noticed earlier.

**Comment by mdbaniani** [comment]
the example mentioned in readme file includes capital letters. seems to need a fix:

> MP3 filenames must be in the following format for the player to recognize them:

> ...

> For example: violin_C4.mp3
